### ISSUE TITLE
Add to postmarketOS wiki

### ISSUE THREAD

**Issue by plata** [alexander-pav/MultiBoot#1]
It would be great to have the instructions in the [postmarketOS wiki](https://wiki.postmarketos.org/wiki/Xiaomi_Poco_F1_(xiaomi-beryllium)). Probably without the Windows part, though.

**Comment by adamproject4444** [comment]
Hello :D! uhm i just have a question is it possible to just use a dual boot between pmOS and android?

**Comment by plata** [comment]
Closed due to inactivity.
